/*
 * admin_panel.h - Embedded admin panel HTML
 * Auto-generated - do not edit directly
 * Source: contrib/admin-panel.html
 * Generate: python3 utils/generate_admin_panel_h.py
 */

#ifndef ADMIN_PANEL_H
#define ADMIN_PANEL_H

static const char *admin_panel_html =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Kannel Admin</title>\n"
"    <style>\n"
"        * { box-sizing: border-box; margin: 0; padding: 0; }\n"
"        body {\n"
"            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
"            background: #0f1419;\n"
"            color: #e7e9ea;\n"
"            min-height: 100vh;\n"
"        }\n"
"        .login-screen {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            min-height: 100vh;\n"
"            padding: 20px;\n"
"        }\n"
"        .login-box {\n"
"            background: #16181c;\n"
"            border: 1px solid #2f3336;\n"
"            border-radius: 16px;\n"
"            padding: 40px;\n"
"            width: 100%;\n"
"            max-width: 360px;\n"
"            text-align: center;\n"
"        }\n"
"        .login-box h1 { font-size: 24px; margin-bottom: 8px; }\n"
"        .login-box p { color: #71767b; font-size: 14px; margin-bottom: 24px; }\n"
"        .login-box input {\n"
"            width: 100%;\n"
"            padding: 12px 16px;\n"
"            background: #1d1f23;\n"
"            border: 1px solid #2f3336;\n"
"            border-radius: 8px;\n"
"            color: #e7e9ea;\n"
"            font-size: 15px;\n"
"            margin-bottom: 16px;\n"
"        }\n"
"        .login-box input:focus { outline: none; border-color: #1d9bf0; }\n"
"        .login-box .btn { width: 100%; padding: 12px; font-size: 15px; }\n"
"        .login-error { color: #f4212e; font-size: 13px; margin-bottom: 16px; display: none; }\n"
"        .app { display: none; padding: 20px; }\n"
"        .header {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            margin-bottom: 24px;\n"
"            padding-bottom: 16px;\n"
"            border-bottom: 1px solid #2f3336;\n"
"        }\n"
"        .header h1 { font-size: 24px; font-weight: 600; }\n"
"        .header-right { display: flex; align-items: center; gap: 16px; }\n"
"        .health {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 8px;\n"
"            padding: 8px 16px;\n"
"            border-radius: 20px;\n"
"            font-size: 14px;\n"
"            font-weight: 500;\n"
"        }\n"
"        .health.ok { background: #0d3d2e; color: #00ba7c; }\n"
"        .health.error { background: #3d1d1d; color: #f4212e; }\n"
"        .health.loading { background: #2f3336; color: #71767b; }\n"
"        .health-dot {\n"
"            width: 8px;\n"
"            height: 8px;\n"
"            border-radius: 50%;\n"
"            background: currentColor;\n"
"        }\n"
"        .logout-btn {\n"
"            background: none;\n"
"            border: 1px solid #2f3336;\n"
"            color: #71767b;\n"
"            padding: 8px 16px;\n"
"            border-radius: 20px;\n"
"            font-size: 13px;\n"
"            cursor: pointer;\n"
"        }\n"
"        .logout-btn:hover { border-color: #f4212e; color: #f4212e; }\n"
"        .grid {\n"
"            display: grid;\n"
"            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n"
"            gap: 16px;\n"
"            margin-bottom: 24px;\n"
"        }\n"
"        .card {\n"
"            background: #16181c;\n"
"            border: 1px solid #2f3336;\n"
"            border-radius: 12px;\n"
"            padding: 20px;\n"
"        }\n"
"        .card h2 {\n"
"            font-size: 14px;\n"
"            color: #71767b;\n"
"            text-transform: uppercase;\n"
"            letter-spacing: 0.5px;\n"
"            margin-bottom: 16px;\n"
"        }\n"
"        .stat {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            padding: 8px 0;\n"
"            border-bottom: 1px solid #2f3336;\n"
"        }\n"
"        .stat:last-child { border-bottom: none; }\n"
"        .stat-label { color: #71767b; }\n"
"        .stat-value { font-weight: 600; font-variant-numeric: tabular-nums; }\n"
"        .smsc-list { display: flex; flex-direction: column; gap: 12px; }\n"
"        .smsc-item {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            padding: 12px;\n"
"            background: #1d1f23;\n"
"            border-radius: 8px;\n"
"        }\n"
"        .smsc-info { display: flex; flex-direction: column; gap: 4px; }\n"
"        .smsc-id { font-weight: 600; }\n"
"        .smsc-status { font-size: 12px; }\n"
"        .smsc-status.online { color: #00ba7c; }\n"
"        .smsc-status.offline { color: #f4212e; }\n"
"        .smsc-status.connecting { color: #ffd400; }\n"
"        .smsc-stats { font-size: 12px; color: #71767b; }\n"
"        .btn {\n"
"            padding: 8px 16px;\n"
"            border: none;\n"
"            border-radius: 6px;\n"
"            font-size: 13px;\n"
"            font-weight: 600;\n"
"            cursor: pointer;\n"
"            transition: opacity 0.15s;\n"
"        }\n"
"        .btn:hover { opacity: 0.85; }\n"
"        .btn:disabled { opacity: 0.5; cursor: not-allowed; }\n"
"        .btn-start { background: #00ba7c; color: #fff; }\n"
"        .btn-stop { background: #f4212e; color: #fff; }\n"
"        .btn-primary { background: #1d9bf0; color: #fff; }\n"
"        .btn-secondary { background: #2f3336; color: #e7e9ea; }\n"
"        .form-group { margin-bottom: 16px; }\n"
"        .form-group label {\n"
"            display: block;\n"
"            font-size: 13px;\n"
"            color: #71767b;\n"
"            margin-bottom: 6px;\n"
"        }\n"
"        .form-group input, .form-group textarea, .form-group select {\n"
"            width: 100%;\n"
"            padding: 10px 12px;\n"
"            background: #1d1f23;\n"
"            border: 1px solid #2f3336;\n"
"            border-radius: 6px;\n"
"            color: #e7e9ea;\n"
"            font-size: 14px;\n"
"        }\n"
"        .form-group input:focus, .form-group textarea:focus, .form-group select:focus {\n"
"            outline: none;\n"
"            border-color: #1d9bf0;\n"
"        }\n"
"        .form-row { display: flex; gap: 12px; }\n"
"        .form-row .form-group { flex: 1; }\n"
"        .alert {\n"
"            padding: 12px 16px;\n"
"            border-radius: 8px;\n"
"            margin-bottom: 16px;\n"
"            font-size: 14px;\n"
"        }\n"
"        .alert.success { background: #0d3d2e; color: #00ba7c; }\n"
"        .alert.error { background: #3d1d1d; color: #f4212e; }\n"
"        .rates { display: flex; gap: 16px; flex-wrap: wrap; }\n"
"        .rate-item {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"            padding: 12px 20px;\n"
"            background: #1d1f23;\n"
"            border-radius: 8px;\n"
"            min-width: 80px;\n"
"        }\n"
"        .rate-value { font-size: 24px; font-weight: 700; }\n"
"        .rate-label { font-size: 11px; color: #71767b; margin-top: 4px; }\n"
"        .actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 16px; }\n"
"        .uptime { font-size: 13px; color: #71767b; }\n"
"        .tabs { display: flex; gap: 4px; margin-bottom: 20px; }\n"
"        .tab {\n"
"            padding: 10px 20px;\n"
"            background: transparent;\n"
"            border: none;\n"
"            color: #71767b;\n"
"            font-size: 14px;\n"
"            font-weight: 600;\n"
"            cursor: pointer;\n"
"            border-bottom: 2px solid transparent;\n"
"        }\n"
"        .tab.active { color: #e7e9ea; border-bottom-color: #1d9bf0; }\n"
"        .tab-content { display: none; }\n"
"        .tab-content.active { display: block; }\n"
"        .empty { color: #71767b; font-style: italic; padding: 20px; text-align: center; }\n"
"        .refresh-info { font-size: 12px; color: #71767b; }\n"
"        .queue-table { width: 100%; border-collapse: collapse; font-size: 13px; }\n"
"        .queue-table th, .queue-table td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #2f3336; }\n"
"        .queue-table th { color: #71767b; font-weight: 500; background: #1d1f23; }\n"
"        .queue-table tr:hover { background: #1d1f23; }\n"
"        .queue-table .msg-id { font-family: monospace; font-size: 11px; color: #71767b; }\n"
"        .queue-table .msg-text { max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n"
"        .mode-badge { padding: 4px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; text-transform: uppercase; }\n"
"        .mode-badge.admin { background: #0d3d2e; color: #00ba7c; }\n"
"        .mode-badge.readonly { background: #3d2d1d; color: #ffd400; }\n"
"        .github-link { color: #71767b; display: flex; align-items: center; transition: color 0.15s; }\n"
"        .github-link:hover { color: #e7e9ea; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <!-- Login Screen -->\n"
"    <div class=\"login-screen\" id=\"loginScreen\">\n"
"        <div class=\"login-box\">\n"
"            <h1>Kannel Admin</h1>\n"
"            <p>Enter admin password to continue</p>\n"
"            <div class=\"login-error\" id=\"loginError\">Invalid password</div>\n"
"            <input type=\"password\" id=\"loginPassword\" placeholder=\"Password\" autofocus>\n"
"            <button class=\"btn btn-primary\" onclick=\"login()\">Login</button>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Main App -->\n"
"    <div class=\"app\" id=\"app\">\n"
"        <div class=\"header\">\n"
"            <div>\n"
"                <h1>Kannel Admin</h1>\n"
"                <span class=\"uptime\" id=\"uptime\">-</span>\n"
"            </div>\n"
"            <div class=\"header-right\">\n"
"                <span class=\"refresh-info\">Auto-refresh: 5s</span>\n"
"                <div class=\"mode-badge\" id=\"modeBadge\" title=\"Access level\"></div>\n"
"                <div class=\"health loading\" id=\"health\">\n"
"                    <span class=\"health-dot\"></span>\n"
"                    <span>Connecting...</span>\n"
"                </div>\n"
"                <button class=\"logout-btn\" onclick=\"logout()\">Logout</button>\n"
"                <a href=\"https://github.com/vaska94/kannel\" target=\"_blank\" class=\"github-link\" title=\"GitHub\">\n"
"                    <svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z\"/></svg>\n"
"                </a>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div class=\"tabs\">\n"
"            <button class=\"tab active\" data-tab=\"dashboard\">Dashboard</button>\n"
"            <button class=\"tab\" data-tab=\"queue\">Queue</button>\n"
"            <button class=\"tab\" data-tab=\"send\">Send SMS</button>\n"
"            <button class=\"tab\" data-tab=\"controls\">Controls</button>\n"
"        </div>\n"
"\n"
"        <div id=\"dashboard\" class=\"tab-content active\">\n"
"            <div class=\"grid\">\n"
"                <div class=\"card\">\n"
"                    <h2>SMS Traffic</h2>\n"
"                    <div class=\"rates\">\n"
"                        <div class=\"rate-item\">\n"
"                            <span class=\"rate-value\" id=\"smsInRate\">-</span>\n"
"                            <span class=\"rate-label\">IN/min</span>\n"
"                        </div>\n"
"                        <div class=\"rate-item\">\n"
"                            <span class=\"rate-value\" id=\"smsOutRate\">-</span>\n"
"                            <span class=\"rate-label\">OUT/min</span>\n"
"                        </div>\n"
"                    </div>\n"
"                    <div style=\"margin-top: 16px;\">\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Received Total</span>\n"
"                            <span class=\"stat-value\" id=\"smsRecvTotal\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Sent Total</span>\n"
"                            <span class=\"stat-value\" id=\"smsSentTotal\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Queued (recv)</span>\n"
"                            <span class=\"stat-value\" id=\"smsRecvQueued\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Queued (send)</span>\n"
"                            <span class=\"stat-value\" id=\"smsSentQueued\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Store Size</span>\n"
"                            <span class=\"stat-value\" id=\"storeSize\">-</span>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"card\">\n"
"                    <h2>DLR Traffic</h2>\n"
"                    <div class=\"rates\">\n"
"                        <div class=\"rate-item\">\n"
"                            <span class=\"rate-value\" id=\"dlrInRate\">-</span>\n"
"                            <span class=\"rate-label\">IN/min</span>\n"
"                        </div>\n"
"                        <div class=\"rate-item\">\n"
"                            <span class=\"rate-value\" id=\"dlrOutRate\">-</span>\n"
"                            <span class=\"rate-label\">OUT/min</span>\n"
"                        </div>\n"
"                    </div>\n"
"                    <div style=\"margin-top: 16px;\">\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Received</span>\n"
"                            <span class=\"stat-value\" id=\"dlrRecv\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Sent</span>\n"
"                            <span class=\"stat-value\" id=\"dlrSent\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Queued</span>\n"
"                            <span class=\"stat-value\" id=\"dlrQueued\">-</span>\n"
"                        </div>\n"
"                        <div class=\"stat\">\n"
"                            <span class=\"stat-label\">Storage</span>\n"
"                            <span class=\"stat-value\" id=\"dlrStorage\">-</span>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"card\">\n"
"                    <h2>Connected Boxes</h2>\n"
"                    <div id=\"boxesList\" class=\"smsc-list\">\n"
"                        <div class=\"empty\">No boxes connected</div>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"card\">\n"
"                    <h2>SMSC Connections</h2>\n"
"                    <div id=\"smscList\" class=\"smsc-list\">\n"
"                        <div class=\"empty\">Loading...</div>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div id=\"queue\" class=\"tab-content\">\n"
"            <div class=\"card\">\n"
"                <div style=\"display:flex;justify-content:space-between;align-items:center;margin-bottom:16px\">\n"
"                    <h2 style=\"margin:0\">Message Queue</h2>\n"
"                    <button class=\"btn btn-secondary\" onclick=\"fetchQueue()\">Refresh</button>\n"
"                </div>\n"
"                <div id=\"queueList\">\n"
"                    <div class=\"empty\">Click Refresh to load queue</div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div id=\"send\" class=\"tab-content\">\n"
"            <div class=\"card\" style=\"max-width: 500px;\">\n"
"                <h2>Send Test SMS</h2>\n"
"                <div id=\"sendAlert\"></div>\n"
"                <div class=\"form-group\">\n"
"                    <label>From (Sender ID)</label>\n"
"                    <input type=\"text\" id=\"smsFrom\" placeholder=\"KANNEL\">\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label>To (Phone Number)</label>\n"
"                    <input type=\"text\" id=\"smsTo\" placeholder=\"+1234567890\">\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label>Message</label>\n"
"                    <textarea id=\"smsText\" rows=\"4\" placeholder=\"Your message here...\"></textarea>\n"
"                </div>\n"
"                <div class=\"form-row\">\n"
"                    <div class=\"form-group\">\n"
"                        <label>SMSBox</label>\n"
"                        <div style=\"display:flex;gap:8px\">\n"
"                            <select id=\"smsSmsbox\" style=\"flex:1\"><option value=\"\">Select smsbox...</option></select>\n"
"                            <button class=\"btn btn-secondary\" onclick=\"testSmsAuth()\" id=\"testAuthBtn\" title=\"Test if password works with smsbox\">Test</button>\n"
"                        </div>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label>SMSC (optional)</label>\n"
"                        <select id=\"smsSmsc\"><option value=\"\">Default</option></select>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label>DLR Mask</label>\n"
"                    <input type=\"number\" id=\"smsDlrMask\" value=\"31\" min=\"0\" max=\"31\" style=\"max-width:100px\">\n"
"                </div>\n"
"                <button class=\"btn btn-primary\" onclick=\"sendSms()\" id=\"sendBtn\">Send SMS</button>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div id=\"controls\" class=\"tab-content\">\n"
"            <div class=\"grid\">\n"
"                <div class=\"card\">\n"
"                    <h2>Gateway Control</h2>\n"
"                    <div id=\"controlAlert\"></div>\n"
"                    <p style=\"color: #71767b; font-size: 13px; margin-bottom: 16px;\">\n"
"                        Current status: <strong id=\"gwStatus\">-</strong>\n"
"                    </p>\n"
"                    <div class=\"actions\">\n"
"                        <button class=\"btn btn-secondary\" onclick=\"gwCommand('suspend')\">Suspend</button>\n"
"                        <button class=\"btn btn-secondary\" onclick=\"gwCommand('resume')\">Resume</button>\n"
"                        <button class=\"btn btn-secondary\" onclick=\"gwCommand('isolate')\">Isolate</button>\n"
"                        <button class=\"btn btn-secondary\" onclick=\"gwCommand('flush-dlr')\">Flush DLR</button>\n"
"                        <button class=\"btn btn-secondary\" onclick=\"gwCommand('reload-lists')\">Reload Lists</button>\n"
"                    </div>\n"
"                    <div class=\"actions\">\n"
"                        <button class=\"btn btn-secondary\" onclick=\"gwCommand('graceful-restart')\">Graceful Restart</button>\n"
"                        <button class=\"btn btn-stop\" onclick=\"if(confirm('Shutdown gateway?')) gwCommand('shutdown')\">Shutdown</button>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"card\">\n"
"                    <h2>Log Level</h2>\n"
"                    <div class=\"form-row\">\n"
"                        <div class=\"form-group\">\n"
"                            <label>Set Log Level (0=debug, 4=panic)</label>\n"
"                            <input type=\"number\" id=\"logLevel\" value=\"0\" min=\"0\" max=\"4\">\n"
"                        </div>\n"
"                    </div>\n"
"                    <button class=\"btn btn-secondary\" onclick=\"setLogLevel()\">Apply</button>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        let refreshInterval = null;\n"
"        let smsboxes = []; // Store smsbox connection info\n"
"        let isAdminMode = false;\n"
"\n"
"        // Session management\n"
"        function getPassword() {\n"
"            return sessionStorage.getItem('kannel_admin_password');\n"
"        }\n"
"\n"
"        function setPassword(pwd) {\n"
"            sessionStorage.setItem('kannel_admin_password', pwd);\n"
"        }\n"
"\n"
"        function clearPassword() {\n"
"            sessionStorage.removeItem('kannel_admin_password');\n"
"            sessionStorage.removeItem('kannel_admin_mode');\n"
"        }\n"
"\n"
"        function getAdminMode() {\n"
"            return sessionStorage.getItem('kannel_admin_mode') === 'true';\n"
"        }\n"
"\n"
"        function setAdminMode(mode) {\n"
"            isAdminMode = mode;\n"
"            sessionStorage.setItem('kannel_admin_mode', mode ? 'true' : 'false');\n"
"            updateModeBadge();\n"
"        }\n"
"\n"
"        function updateModeBadge() {\n"
"            const el = document.getElementById('modeBadge');\n"
"            if (isAdminMode) {\n"
"                el.className = 'mode-badge admin';\n"
"                el.textContent = 'Admin';\n"
"                el.title = 'Full admin access';\n"
"            } else {\n"
"                el.className = 'mode-badge readonly';\n"
"                el.textContent = 'View Only';\n"
"                el.title = 'Status password - read-only access';\n"
"            }\n"
"        }\n"
"\n"
"        async function checkAdminAccess() {\n"
"            const pwd = getPassword();\n"
"            try {\n"
"                const res = await fetch(`/log-level?password=${encodeURIComponent(pwd)}`);\n"
"                const text = await res.text();\n"
"                setAdminMode(!text.includes('Denied'));\n"
"            } catch (e) {\n"
"                setAdminMode(false);\n"
"            }\n"
"        }\n"
"\n"
"        // Check session on load\n"
"        function checkSession() {\n"
"            if (getPassword()) {\n"
"                isAdminMode = getAdminMode();\n"
"                showApp();\n"
"            }\n"
"        }\n"
"\n"
"        async function login() {\n"
"            const pwd = document.getElementById('loginPassword').value;\n"
"            const errorEl = document.getElementById('loginError');\n"
"\n"
"            try {\n"
"                const res = await fetch(`/status.json?password=${encodeURIComponent(pwd)}`);\n"
"                const text = await res.text();\n"
"                // Check if response is valid JSON (not \"Denied\" text)\n"
"                if (res.ok && text.startsWith('{')) {\n"
"                    JSON.parse(text); // Verify it's valid JSON\n"
"                    setPassword(pwd);\n"
"                    errorEl.style.display = 'none';\n"
"                    showApp();\n"
"                } else {\n"
"                    errorEl.style.display = 'block';\n"
"                    errorEl.textContent = 'Invalid password';\n"
"                }\n"
"            } catch (e) {\n"
"                errorEl.style.display = 'block';\n"
"                errorEl.textContent = e.message.includes('JSON') ? 'Invalid password' : 'Connection failed';\n"
"            }\n"
"        }\n"
"\n"
"        function logout() {\n"
"            clearPassword();\n"
"            if (refreshInterval) clearInterval(refreshInterval);\n"
"            document.getElementById('app').style.display = 'none';\n"
"            document.getElementById('loginScreen').style.display = 'flex';\n"
"            document.getElementById('loginPassword').value = '';\n"
"        }\n"
"\n"
"        function showApp() {\n"
"            document.getElementById('loginScreen').style.display = 'none';\n"
"            document.getElementById('app').style.display = 'block';\n"
"            updateModeBadge();\n"
"            checkAdminAccess();\n"
"            fetchStatus();\n"
"            refreshInterval = setInterval(fetchStatus, 5000);\n"
"        }\n"
"\n"
"        // Enter key for login\n"
"        document.getElementById('loginPassword').addEventListener('keypress', (e) => {\n"
"            if (e.key === 'Enter') login();\n"
"        });\n"
"\n"
"        // Tab switching\n"
"        document.querySelectorAll('.tab').forEach(tab => {\n"
"            tab.addEventListener('click', () => {\n"
"                document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));\n"
"                document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));\n"
"                tab.classList.add('active');\n"
"                document.getElementById(tab.dataset.tab).classList.add('active');\n"
"                // Auto-load queue when switching to queue tab\n"
"                if (tab.dataset.tab === 'queue') fetchQueue();\n"
"            });\n"
"        });\n"
"\n"
"        async function fetchStatus() {\n"
"            const pwd = getPassword();\n"
"            if (!pwd) return;\n"
"\n"
"            try {\n"
"                const res = await fetch(`/status.json?password=${encodeURIComponent(pwd)}`);\n"
"                if (res.status === 403) {\n"
"                    logout();\n"
"                    return;\n"
"                }\n"
"                if (!res.ok) throw new Error('Failed');\n"
"                const data = await res.json();\n"
"                updateDashboard(data);\n"
"                updateHealth(true, data.status);\n"
"            } catch (e) {\n"
"                console.error('Status fetch error:', e);\n"
"                updateHealth(false);\n"
"            }\n"
"        }\n"
"\n"
"        function updateHealth(ok, status) {\n"
"            const el = document.getElementById('health');\n"
"            if (ok) {\n"
"                el.className = 'health ok';\n"
"                el.innerHTML = `<span class=\"health-dot\"></span><span>${status || 'running'}</span>`;\n"
"            } else {\n"
"                el.className = 'health error';\n"
"                el.innerHTML = '<span class=\"health-dot\"></span><span>Offline</span>';\n"
"            }\n"
"        }\n"
"\n"
"        function updateDashboard(data) {\n"
"            const u = data.uptime;\n"
"            document.getElementById('uptime').textContent =\n"
"                `Uptime: ${u.days}d ${u.hours}h ${u.minutes}m ${u.seconds}s`;\n"
"\n"
"            document.getElementById('gwStatus').textContent = data.status;\n"
"\n"
"            const sms = data.sms;\n"
"            document.getElementById('smsInRate').textContent = sms.inbound_rate[1].toFixed(1);\n"
"            document.getElementById('smsOutRate').textContent = sms.outbound_rate[1].toFixed(1);\n"
"            document.getElementById('smsRecvTotal').textContent = sms.received.total.toLocaleString();\n"
"            document.getElementById('smsSentTotal').textContent = sms.sent.total.toLocaleString();\n"
"            document.getElementById('smsRecvQueued').textContent = sms.received.queued;\n"
"            document.getElementById('smsSentQueued').textContent = sms.sent.queued;\n"
"            document.getElementById('storeSize').textContent = sms.store_size;\n"
"\n"
"            const dlr = data.dlr;\n"
"            document.getElementById('dlrInRate').textContent = dlr.inbound_rate[1].toFixed(1);\n"
"            document.getElementById('dlrOutRate').textContent = dlr.outbound_rate[1].toFixed(1);\n"
"            document.getElementById('dlrRecv').textContent = dlr.received.toLocaleString();\n"
"            document.getElementById('dlrSent').textContent = dlr.sent.toLocaleString();\n"
"            document.getElementById('dlrQueued').textContent = dlr.queued;\n"
"            document.getElementById('dlrStorage').textContent = dlr.storage;\n"
"\n"
"            updateSmscList(data.smscs || []);\n"
"            updateBoxesList(data.boxes || []);\n"
"        }\n"
"\n"
"        function updateSmscList(smscs) {\n"
"            const el = document.getElementById('smscList');\n"
"            const select = document.getElementById('smsSmsc');\n"
"\n"
"            // Update SMSC dropdown for send form\n"
"            const currentVal = select.value;\n"
"            select.innerHTML = '<option value=\"\">Default</option>' +\n"
"                smscs.map(s => `<option value=\"${s.id}\">${s.id}</option>`).join('');\n"
"            select.value = currentVal;\n"
"\n"
"            if (!smscs.length) {\n"
"                el.innerHTML = '<div class=\"empty\">No SMSCs configured</div>';\n"
"                return;\n"
"            }\n"
"            el.innerHTML = smscs.map(s => {\n"
"                const statusClass = s.status === 'online' ? 'online' :\n"
"                                   s.status.includes('connecting') ? 'connecting' : 'offline';\n"
"                // Show Stop for online OR connecting states (SMSC is running)\n"
"                const isRunning = s.status === 'online' || s.status.includes('connecting');\n"
"                return `\n"
"                    <div class=\"smsc-item\">\n"
"                        <div class=\"smsc-info\">\n"
"                            <span class=\"smsc-id\">${s.id || s.name}</span>\n"
"                            <span class=\"smsc-status ${statusClass}\">${s.status}</span>\n"
"                            <span class=\"smsc-stats\">\n"
"                                SMS: ${s.sms.received}/${s.sms.sent} |\n"
"                                DLR: ${s.dlr.received}/${s.dlr.sent} |\n"
"                                Q: ${s.queued} | F: ${s.failed}\n"
"                            </span>\n"
"                        </div>\n"
"                        <button class=\"btn ${isRunning ? 'btn-stop' : 'btn-start'}\"\n"
"                                onclick=\"smscCommand('${isRunning ? 'stop' : 'start'}', '${s.id}')\">\n"
"                            ${isRunning ? 'Stop' : 'Start'}\n"
"                        </button>\n"
"                    </div>\n"
"                `;\n"
"            }).join('');\n"
"        }\n"
"\n"
"        function updateBoxesList(boxes) {\n"
"            const el = document.getElementById('boxesList');\n"
"            const smsboxSelect = document.getElementById('smsSmsbox');\n"
"\n"
"            // Store smsboxes for Send SMS feature\n"
"            smsboxes = boxes.filter(b => b.type === 'smsbox' && b.http_port > 0);\n"
"\n"
"            // Update smsbox dropdown\n"
"            const currentSmsbox = smsboxSelect.value;\n"
"            smsboxSelect.innerHTML = smsboxes.length === 0\n"
"                ? '<option value=\"\">No smsbox available</option>'\n"
"                : smsboxes.map((b, i) =>\n"
"                    `<option value=\"${i}\">${b.id || 'smsbox'} (${b.ip}:${b.http_port})</option>`\n"
"                  ).join('');\n"
"            if (currentSmsbox && smsboxSelect.querySelector(`option[value=\"${currentSmsbox}\"]`)) {\n"
"                smsboxSelect.value = currentSmsbox;\n"
"            }\n"
"\n"
"            if (!boxes.length) {\n"
"                el.innerHTML = '<div class=\"empty\">No boxes connected</div>';\n"
"                return;\n"
"            }\n"
"            el.innerHTML = boxes.map(b => `\n"
"                <div class=\"smsc-item\">\n"
"                    <div class=\"smsc-info\">\n"
"                        <span class=\"smsc-id\">${b.type}: ${b.id || 'unnamed'}</span>\n"
"                        <span class=\"smsc-stats\">IP: ${b.ip}${b.http_port ? ':' + b.http_port : ''} | Queue: ${b.queue}</span>\n"
"                    </div>\n"
"                </div>\n"
"            `).join('');\n"
"        }\n"
"\n"
"        async function smscCommand(action, smscId) {\n"
"            const pwd = getPassword();\n"
"            try {\n"
"                const res = await fetch(`/${action}-smsc?password=${encodeURIComponent(pwd)}&smsc=${encodeURIComponent(smscId)}`);\n"
"                const text = await res.text();\n"
"                alert(text);\n"
"                fetchStatus();\n"
"            } catch (e) {\n"
"                alert('Error: ' + e.message);\n"
"            }\n"
"        }\n"
"\n"
"        async function gwCommand(cmd) {\n"
"            const pwd = getPassword();\n"
"            const el = document.getElementById('controlAlert');\n"
"            try {\n"
"                const res = await fetch(`/${cmd}?password=${encodeURIComponent(pwd)}`);\n"
"                const text = await res.text();\n"
"                el.innerHTML = `<div class=\"alert success\">${text}</div>`;\n"
"                fetchStatus();\n"
"            } catch (e) {\n"
"                el.innerHTML = `<div class=\"alert error\">Error: ${e.message}</div>`;\n"
"            }\n"
"            setTimeout(() => el.innerHTML = '', 5000);\n"
"        }\n"
"\n"
"        async function setLogLevel() {\n"
"            const pwd = getPassword();\n"
"            const level = document.getElementById('logLevel').value;\n"
"            try {\n"
"                const res = await fetch(`/log-level?password=${encodeURIComponent(pwd)}&level=${level}`);\n"
"                const text = await res.text();\n"
"                alert(text);\n"
"            } catch (e) {\n"
"                alert('Error: ' + e.message);\n"
"            }\n"
"        }\n"
"\n"
"        async function fetchQueue() {\n"
"            const pwd = getPassword();\n"
"            const el = document.getElementById('queueList');\n"
"            el.innerHTML = '<div class=\"empty\">Loading...</div>';\n"
"\n"
"            try {\n"
"                const res = await fetch(`/store-status?password=${encodeURIComponent(pwd)}`);\n"
"                const text = await res.text();\n"
"                const lines = text.trim().split('\\n');\n"
"\n"
"                if (lines.length <= 1) {\n"
"                    el.innerHTML = '<div class=\"empty\">Queue is empty</div>';\n"
"                    return;\n"
"                }\n"
"\n"
"                // Parse the store-status output\n"
"                // Format: [SMS ID] [Type] [Time] [Sender] [Receiver] [SMSC ID] [BOX ID] [Flags] [UDH] [Message]\n"
"                const rows = lines.slice(1).map(line => {\n"
"                    const match = line.match(/\\[([^\\]]*)\\]/g);\n"
"                    if (!match || match.length < 10) return null;\n"
"                    const clean = match.map(m => m.slice(1, -1));\n"
"                    return {\n"
"                        id: clean[0],\n"
"                        type: clean[1],\n"
"                        time: clean[2],\n"
"                        sender: clean[3],\n"
"                        receiver: clean[4],\n"
"                        smsc: clean[5],\n"
"                        boxc: clean[6],\n"
"                        flags: clean[7],\n"
"                        udh: clean[8],\n"
"                        message: clean[9]\n"
"                    };\n"
"                }).filter(Boolean);\n"
"\n"
"                if (!rows.length) {\n"
"                    el.innerHTML = '<div class=\"empty\">Queue is empty</div>';\n"
"                    return;\n"
"                }\n"
"\n"
"                el.innerHTML = `\n"
"                    <table class=\"queue-table\">\n"
"                        <thead>\n"
"                            <tr><th>Time</th><th>From</th><th>To</th><th>SMSC</th><th>Message</th><th>ID</th></tr>\n"
"                        </thead>\n"
"                        <tbody>\n"
"                            ${rows.map(r => `\n"
"                                <tr>\n"
"                                    <td>${r.time}</td>\n"
"                                    <td>${r.sender}</td>\n"
"                                    <td>${r.receiver}</td>\n"
"                                    <td>${r.smsc || '-'}</td>\n"
"                                    <td class=\"msg-text\" title=\"${r.message}\">${r.message}</td>\n"
"                                    <td class=\"msg-id\">${r.id.substring(0, 8)}...</td>\n"
"                                </tr>\n"
"                            `).join('')}\n"
"                        </tbody>\n"
"                    </table>\n"
"                `;\n"
"            } catch (e) {\n"
"                el.innerHTML = `<div class=\"empty\">Error: ${e.message}</div>`;\n"
"            }\n"
"        }\n"
"\n"
"        async function testSmsAuth() {\n"
"            const pwd = getPassword();\n"
"            const el = document.getElementById('sendAlert');\n"
"            const smsboxIdx = document.getElementById('smsSmsbox').value;\n"
"\n"
"            if (!smsboxes.length) {\n"
"                el.innerHTML = '<div class=\"alert error\">No smsbox connected</div>';\n"
"                return;\n"
"            }\n"
"\n"
"            const box = smsboxes[smsboxIdx !== '' ? parseInt(smsboxIdx) : 0];\n"
"            if (!box) {\n"
"                el.innerHTML = '<div class=\"alert error\">Please select an smsbox</div>';\n"
"                return;\n"
"            }\n"
"\n"
"            try {\n"
"                // Test auth by making request without required fields\n"
"                const smsboxUrl = `${location.protocol}//${box.ip}:${box.http_port}`;\n"
"                const res = await fetch(`${smsboxUrl}/cgi-bin/sendsms?username=admin&password=${encodeURIComponent(pwd)}`);\n"
"                const data = await res.text();\n"
"\n"
"                if (data.includes('Authorization failed')) {\n"
"                    el.innerHTML = '<div class=\"alert error\">Auth failed - password not valid for smsbox. Add sendsms-user with admin-password.</div>';\n"
"                } else {\n"
"                    el.innerHTML = '<div class=\"alert success\">Auth OK - password works with smsbox</div>';\n"
"                }\n"
"            } catch (e) {\n"
"                el.innerHTML = `<div class=\"alert error\">Connection error: ${e.message}</div>`;\n"
"            }\n"
"            setTimeout(() => el.innerHTML = '', 5000);\n"
"        }\n"
"\n"
"        async function sendSms() {\n"
"            const pwd = getPassword();\n"
"            const el = document.getElementById('sendAlert');\n"
"            const btn = document.getElementById('sendBtn');\n"
"\n"
"            const from = document.getElementById('smsFrom').value;\n"
"            const to = document.getElementById('smsTo').value;\n"
"            const text = document.getElementById('smsText').value;\n"
"            const smsc = document.getElementById('smsSmsc').value;\n"
"            const dlrMask = document.getElementById('smsDlrMask').value;\n"
"            const smsboxIdx = document.getElementById('smsSmsbox').value;\n"
"\n"
"            if (!to || !text) {\n"
"                el.innerHTML = '<div class=\"alert error\">To and Message are required</div>';\n"
"                return;\n"
"            }\n"
"\n"
"            // Get smsbox from selection\n"
"            if (!smsboxes.length) {\n"
"                el.innerHTML = '<div class=\"alert error\">No smsbox connected</div>';\n"
"                return;\n"
"            }\n"
"\n"
"            const box = smsboxes[smsboxIdx !== '' ? parseInt(smsboxIdx) : 0];\n"
"            if (!box) {\n"
"                el.innerHTML = '<div class=\"alert error\">Please select an smsbox</div>';\n"
"                return;\n"
"            }\n"
"\n"
"            btn.disabled = true;\n"
"            btn.textContent = 'Sending...';\n"
"\n"
"            try {\n"
"                const smsboxUrl = `${location.protocol}//${box.ip}:${box.http_port}`;\n"
"                let url = `${smsboxUrl}/cgi-bin/sendsms?username=admin&password=${encodeURIComponent(pwd)}` +\n"
"                    `&to=${encodeURIComponent(to)}&text=${encodeURIComponent(text)}`;\n"
"                if (from) url += `&from=${encodeURIComponent(from)}`;\n"
"                if (smsc) url += `&smsc=${encodeURIComponent(smsc)}`;\n"
"                if (dlrMask) url += `&dlr-mask=${dlrMask}`;\n"
"\n"
"                const res = await fetch(url);\n"
"                const data = await res.text();\n"
"\n"
"                if (res.ok && !data.includes('Authorization failed')) {\n"
"                    el.innerHTML = `<div class=\"alert success\">${data}</div>`;\n"
"                } else {\n"
"                    el.innerHTML = `<div class=\"alert error\">${data}</div>`;\n"
"                }\n"
"            } catch (e) {\n"
"                el.innerHTML = `<div class=\"alert error\">Error: ${e.message}</div>`;\n"
"            }\n"
"\n"
"            btn.disabled = false;\n"
"            btn.textContent = 'Send SMS';\n"
"            setTimeout(() => el.innerHTML = '', 5000);\n"
"        }\n"
"\n"
"        // Check for existing session\n"
"        checkSession();\n"
"    </script>\n"
"</body>\n"
"</html>\n"
"";

#endif /* ADMIN_PANEL_H */
