#!/bin/sh

usage()
{
	echo "usage: $0 [--cflags] [--libs] [--version]"
	exit 0
}

cflags=no
libs=no
version=no

test "$1" || usage

while test "$1"; do
	case "$1" in
	--cflags )
		cflags=yes
		;;
	--libs )
		libs=yes
		;;
	--version )
		version=yes
		;;
	* )
		usage
		;;
	esac
	shift
done

test "$cflags" = yes && cat << FOO
-I/usr/local/include/kannel -g -O2 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_LARGE_FILES= -DBROKEN_PTHREADS=1 -I/usr/include/libxml2 -I/usr/include/hiredis
FOO

test "$libs" = yes && cat << FOO
-L/usr/local/lib/kannel -lgw -lwap -lgwlib -lrt -lresolv -lnsl -lm  -lpthread -lxml2 -lm -pthread -lz -llzma -pthread -lpthread -licuuc -licudata -lpthread -lm -L/usr/lib -lhiredis 
FOO

test "$version" = yes && cat << FOO
1.4.5
FOO

