#! /bin/sh
set -x
set -e

# Check for automake
amvers="no"
if automake --version >/dev/null 2>&1; then
  # Get version number and check if it's >= 1.5
  am_version="`automake --version | head -1 | sed 's/.*automake[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`"
  am_major="`echo $am_version | cut -d. -f1`"
  am_minor="`echo $am_version | cut -d. -f2`"

  # Check if version is >= 1.5
  if test "$am_major" -gt 1 -o \( "$am_major" -eq 1 -a "$am_minor" -ge 5 \); then
    amvers=""
  else
    amvers="no"
  fi
fi

if test "$amvers" = "no"; then
  set +x
  echo "$0: you need automake version 1.5 or later"
  exit 1
fi

# Check for libtool
libtoolize="no"
if glibtoolize --version >/dev/null 2>&1; then
  libtoolize="glibtoolize"
elif libtoolize --version >/dev/null 2>&1; then
  libtoolize="libtoolize"
fi

if test "$libtoolize" = "no"; then
  set +x
  echo "$0: you need libtool"
  exit 1
fi

# Remove old cruft
set +x; for x in aclocal.m4 configure config.guess config.log config.sub config.cache config.h.in config.h compile libtool.m4 ltoptions.m4 ltsugar.m4 ltversion.m4 ltmain.sh libtool ltconfig missing mkinstalldirs depcomp install-sh; do rm -f $x autotools/$x; done; rm -Rf autom4te.cache; set -x
if test ! -d autotools; then mkdir autotools; fi

# Bootstrap package
${libtoolize} --copy --force
if test -f "ltmain.sh"; then
  echo "$0: working around a minor libtool issue"
  mv ltmain.sh autotools/
fi

aclocal${amvers} -I autotools
autoconf
autoheader
#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake${amvers} --add-missing --copy --include-deps
automake${amvers} --add-missing --copy
